LOAD DATA LOCAL INFILE '/root/node4_2022-01-31/csv/plot22:00:01.csv'
#LOAD DATA LOCAL INFILE '/root/test_file.csv'
INTO TABLE flow
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '\"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
